name: CICD - Test Code

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to comment on files in a PR
      issues: write         # Needed to comment on the main PR thread

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear GitHub Actions cache
        run: rm -rf ~/.cache/actions

      - name: Scan NPM package for Malware
        uses: ossprey/gh-action@main
        with:
          package: "javascript/npm_simple_math"
          mode: "npm"
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Yarn package for Malware
        uses: ossprey/gh-action@main
        with:
          package: "javascript/yarn_simple_math"
          mode: "yarn"
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Python package for Malware
        uses: ossprey/gh-action@main
        with:
          package: "python/simple_math"
          mode: "pipenv"
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Compromised python package for Malware
        uses: ossprey/gh-action@main
        with:
          package: "python/compromised_package"
          mode: "python-requirements"
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

