
name: CICD - Test Code

on:
  pull_request:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to comment on files in a PR
      issues: write         # Needed to comment on the main PR thread

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear GitHub Actions cache
        run: rm -rf ~/.cache/actions

      - name: Scan Package for Malware
        uses: ossprey/gh-action@v1.0.0
        with:
          package: simple_math
          requirements: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

